import { redirect } from 'next/navigation'
import DashboardShell from '@/components/DashboardShell'
import FollowupReadyMessages from '@/components/FollowupReadyMessages'
import { createClient } from '@/lib/supabase/server'
import { createTask, saveFollowupNote, clearStudentFollowup } from './actions'

export default async function Followup({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){
 const params=searchParams?await searchParams:{}; const q=String(params.q||'').trim().toLowerCase(); const filterClass=String(params.class||'')
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/auth/login')
 const {data:m}=await supabase.from('memberships').select('tenant_id,tenants(name)').eq('user_id',user.id).maybeSingle(); if(!m) redirect('/dashboard')
 const tenant=(m.tenants as any)?.name||'مساحتي التعليمية'
 const [{data:classes},{data:students},{data:tasks},{data:attendance},{data:subs},{data:notes},{data:messages}]=await Promise.all([
  supabase.from('classes').select('id,name').eq('tenant_id',m.tenant_id).order('name'),
  supabase.from('students').select('id,full_name,class_id,classes(name)').eq('tenant_id',m.tenant_id).order('full_name').limit(300),
  supabase.from('tasks').select('id,title,class_id,due_date,starts_on,task_type,grade,is_published,created_at,classes(name)').eq('tenant_id',m.tenant_id).order('created_at',{ascending:false}).limit(80),
  supabase.from('attendance_records').select('id,student_id,status,attendance_date').eq('tenant_id',m.tenant_id).order('attendance_date',{ascending:false}).limit(1500),
  supabase.from('task_submissions').select('task_id,student_id,status').eq('tenant_id',m.tenant_id).limit(2500),
  supabase.from('student_followup_notes').select('student_id,note,updated_at').eq('tenant_id',m.tenant_id).limit(500),
  supabase.from('outbound_messages').select('id,student_id,channel,body,status,created_at,students(full_name,class_id,classes(name))').eq('tenant_id',m.tenant_id).order('created_at',{ascending:false}).limit(80)
 ])
 const visible=(students||[]).filter((s:any)=>(!filterClass||s.class_id===filterClass)&&(!q||s.full_name.toLowerCase().includes(q)))
 const totalMissing=(subs||[]).filter((x:any)=>x.status==='missing').length,totalSubmitted=(subs||[]).filter((x:any)=>x.status==='submitted').length,totalAbsences=(attendance||[]).filter((a:any)=>a.status==='absent').length
 const noteMap=new Map((notes||[]).map((n:any)=>[n.student_id,n.note]))
 const subByStudent=new Map<string,{submitted:number,missing:number}>();for(const x of subs||[]){const v=subByStudent.get((x as any).student_id)||{submitted:0,missing:0};if((x as any).status==='submitted')v.submitted++;if((x as any).status==='missing')v.missing++;subByStudent.set((x as any).student_id,v)}
 const absByStudent=new Map<string,number>();for(const a of attendance||[]){if((a as any).status==='absent')absByStudent.set((a as any).student_id,(absByStudent.get((a as any).student_id)||0)+1)}
 const today=new Date().toISOString().slice(0,10)
 return <DashboardShell active="/followup" tenant={tenant}><div className="bankContent followWorkspace">
  <section className="followHero"><div><span className="followPill">متابعة فعلية • مترابطة</span><h1>متابعة الطلاب والطالبات</h1><p>حدّثي المهام والغياب والملاحظة، وتُحفظ التغييرات مباشرة داخل مصرف التعليم.</p></div><div className="followHeroIcon">✓</div></section>
  <section className="followStats"><article><span>إجمالي الطلاب/الطالبات</span><strong>{students?.length||0}</strong></article><article><span>المهام غير المسلمة</span><strong>{totalMissing}</strong></article><article><span>المهام المسلمة</span><strong>{totalSubmitted}</strong></article><article><span>إجمالي الغياب</span><strong>{totalAbsences}</strong></article><article><span>حالة الربط</span><strong className="live">مباشر</strong></article></section>
  <section className="followPanel">
   <form className="followFilters" method="get"><input name="q" defaultValue={String(params.q||'')} placeholder="ابحثي باسم الطالب/ة"/><select name="class" defaultValue={filterClass}><option value="">كل الفصول</option>{classes?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn btn-light">بحث</button></form>
   <div className="followBulkBar"><span>المتابعة محسوبة من سجلات المهام الفعلية</span><span className="followHint">يمكن مسح سجل طالب من زر «حذف المهام» داخل صفه.</span></div>
   <div className="tableWrap"><table className="followTable"><thead><tr><th>الطالب/ة</th><th>الفصل</th><th>المهام المسلمة</th><th>المهام غير المسلمة</th><th>الغياب</th><th>آخر ملاحظة</th><th>حفظ</th></tr></thead><tbody>{visible.map((s:any)=>{const c=subByStudent.get(s.id)||{submitted:0,missing:0};return <tr key={s.id}><td><b>{s.full_name}</b></td><td>{s.classes?.name||'—'}</td><td><span className="countBox green">{c.submitted}</span></td><td><span className="countBox red">{c.missing}</span></td><td><span className="countBox">{absByStudent.get(s.id)||0}</span></td><td><form action={saveFollowupNote} className="noteInline"><input type="hidden" name="student_id" value={s.id}/><input name="note" maxLength={500} defaultValue={String(noteMap.get(s.id)||'')} placeholder="اكتبي ملاحظة"/><button className="miniSave">حفظ</button></form></td><td><form action={clearStudentFollowup}><input type="hidden" name="student_id" value={s.id}/><button className="miniDanger" title="يمسح حالات تسليم المهام المسجلة لهذا الطالب">حذف المهام</button></form></td></tr>})}</tbody></table></div>
  </section>
  <section className="followTaskArea"><FollowupReadyMessages classes={(classes||[]).map(c=>({id:c.id,name:c.name}))}/><div className="followTaskCard"><div className="followCardTitle"><span>✓</span><div><h2>المهام الأدائية</h2><p>إنشاء مهمة ونشرها مباشرة على طلاب/طالبات الفصل المحدد.</p></div></div><form action={createTask} className="taskForm"><label className="field full"><span>عنوان المهمة</span><input name="title" required maxLength={180} placeholder="مثال: مشروع الفصل الدراسي"/></label><label className="field"><span>نوع المهمة</span><select name="task_type" defaultValue="واجب"><option>واجب</option><option>مهمة أدائية</option><option>مشروع</option><option>نشاط</option><option>أخرى</option></select></label><label className="field"><span>نوع المهمة الأخرى</span><input name="other_type" maxLength={80} placeholder="اكتبي نوع المهمة"/></label><label className="field"><span>الفصل</span><select name="class_id" required defaultValue=""><option value="" disabled>اختاري الفصل</option>{classes?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span>الدرجة</span><input name="grade" type="number" min="0" max="9999" step="0.5" defaultValue="0"/></label><label className="field"><span>تاريخ البداية</span><input name="starts_on" type="date" defaultValue={today}/></label><label className="field"><span>تاريخ نهاية المهمة</span><input name="due_date" type="date"/></label><label className="publishCheck"><input type="checkbox" name="is_published" defaultChecked/><span>منشورة للطلاب</span></label><div className="taskButtons"><button type="reset" className="btn btn-light">تفريغ الحقول</button><button className="btn btn-primary">حفظ ونشر المهمة</button></div></form>
   <div className="taskArchive"><h3>المهام المحفوظة</h3>{!tasks?.length?<p className="muted">لا توجد مهام أدائية محفوظة حتى الآن.</p>:<div className="tableWrap"><table><thead><tr><th>المهمة</th><th>النوع</th><th>الفصل</th><th>الدرجة</th><th>البداية</th><th>النهاية</th><th>الحالة</th></tr></thead><tbody>{tasks.slice(0,20).map((t:any)=><tr key={t.id}><td>{t.title}</td><td>{t.task_type||'واجب'}</td><td>{t.classes?.name||'—'}</td><td>{t.grade??0}</td><td>{t.starts_on||'—'}</td><td>{t.due_date||'—'}</td><td><span className={`status ${t.is_published?'sent':'queued'}`}>{t.is_published?'منشورة':'مسودة'}</span></td></tr>)}</tbody></table></div>}</div>
  </div></section>
  <section className="followArchive"><div className="followCardTitle"><span>▤</span><div><h2>أرشيف الرسائل</h2><p>جميع الرسائل المحفوظة مع تاريخ الإرسال وحالة المزود.</p></div></div><div className="tableWrap"><table><thead><tr><th>التاريخ</th><th>الطالب/ة</th><th>الفصل</th><th>الرسالة</th><th>القناة</th><th>الحالة</th></tr></thead><tbody>{(messages||[]).map((msg:any)=><tr key={msg.id}><td>{new Date(msg.created_at).toLocaleDateString('ar-SA')}</td><td>{msg.students?.full_name||'—'}</td><td>{msg.students?.classes?.name||'—'}</td><td className="messageCell">{msg.body}</td><td>{msg.channel==='whatsapp'?'واتساب':'SMS'}</td><td><span className={`status ${msg.status}`}>{msg.status==='sent'?'تم الإرسال':msg.status==='failed'?'فشل':'قيد الإرسال'}</span></td></tr>)}</tbody></table></div>{!messages?.length&&<p className="muted">لا توجد رسائل محفوظة حتى الآن.</p>}</section>
 </div></DashboardShell>
}
