import Link from 'next/link'
import { redirect } from 'next/navigation'
import DashboardShell from '@/components/DashboardShell'
import { createClient } from '@/lib/supabase/server'

export default async function Dashboard(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login')
 const {data:m}=await supabase.from('memberships').select('role,tenant_id,tenants(name)').eq('user_id',user.id).maybeSingle()
 if(!m)return <main className="authWrap"><section className="card authCard"><h1>الحساب يحتاج تهيئة</h1><p className="muted">تم إنشاء المستخدم، لكن مساحة الاشتراك لم تُنشأ بعد.</p></section></main>
 const [students,classes,members,sub,messages,attendance]=await Promise.all([
  supabase.from('students').select('*',{count:'exact',head:true}).eq('tenant_id',m.tenant_id),
  supabase.from('classes').select('*',{count:'exact',head:true}).eq('tenant_id',m.tenant_id),
  supabase.from('memberships').select('*',{count:'exact',head:true}).eq('tenant_id',m.tenant_id),
  supabase.from('subscriptions').select('status,current_period_end,plan_code').eq('tenant_id',m.tenant_id).maybeSingle(),
  supabase.from('outbound_messages').select('*',{count:'exact',head:true}).eq('tenant_id',m.tenant_id),
  supabase.from('attendance_records').select('status,attendance_date').eq('tenant_id',m.tenant_id).eq('attendance_date',new Date().toISOString().slice(0,10))
 ])
 const tenant=(m.tenants as any)?.name||'مساحتي التعليمية';const status=sub.data?.status||'غير مفعّل';const absent=(attendance.data||[]).filter((x:any)=>x.status==='absent').length
 return <DashboardShell active="/dashboard" tenant={tenant}><div className="bankContent">
  <section className="bankHero"><div className="welcomeCard"><span className="badge">● الحساب التعليمي {status==='active'?'نشط':status==='trialing'?'تجريبي':'قيد المراجعة'}</span><h1>أهلًا بك في مصرف التعليم</h1><p>إدارة صفوفك وطلابك والمتابعة والتواصل مع أولياء الأمور من مساحة مستقلة خاصة بحسابك.</p><div className="actions"><Link className="btn btn-primary" href="/students">+ إضافة طالب</Link><Link className="btn btn-light" href="/messages">إرسال رسالة لولي أمر</Link></div></div><div className="memberCard"><div style={{display:'flex',justifyContent:'space-between'}}><b>بطاقة الاشتراك</b><span className="chip"/></div><h3>مصرف التعليم</h3><small>{sub.data?.plan_code==='teacher'?'الباقة المهنية':sub.data?.plan_code||'الباقة'}</small><div className="cardNo">•••• &nbsp; {String(m.tenant_id).slice(0,4)} &nbsp; 2026</div><div style={{display:'flex',justifyContent:'space-between',marginTop:20,fontSize:12}}><span>الحالة: {status}</span><span>تجديد شهري</span></div></div></section>
  <div className="grid4"><div className="card metric"><small>الطلاب</small><strong>{students.count||0}</strong></div><div className="card metric"><small>الفصول</small><strong>{classes.count||0}</strong></div><div className="card metric"><small>المعلمين والأعضاء</small><strong>{members.count||0}</strong></div><div className="card metric"><small>رسائل هذا الشهر</small><strong>{messages.count||0}</strong></div></div>
  <section className="card composer teacherHub" style={{marginTop:18}}><div className="teacherHubHead"><div><span className="badge">صفحة المعلم</span><h2>الأقسام</h2><p className="muted">نفس فكرة أقسام بنك الرياضيات، لكن ببيانات وصلاحيات فعلية داخل مصرف التعليم.</p></div><span className="sectionCount">13 قسم</span></div><div className="teacherHubGrid"><Link href="/students" className="teacherHubCard"><span>👩‍🏫</span><b>الفصول والطلاب</b><small>إدارة طلاب الفصول المصرح بها</small></Link><Link href="/advanced" className="teacherHubCard"><span>📊</span><b>لوحة التحكم المتقدمة</b><small>ملخص العمليات والمتابعة</small></Link><Link href="/operations" className="teacherHubCard"><span>🧮</span><b>العمليات</b><small>إيداع وحسم تعليمي</small></Link><Link href="/points" className="teacherHubCard"><span>⭐</span><b>النقاط</b><small>إضافة وحسم وسجل النقاط</small></Link><Link href="/rewards" className="teacherHubCard"><span>🏆</span><b>الجوائز والتحفيز</b><small>جوائز مرتبطة بالنقاط</small></Link><Link href="/data" className="teacherHubCard"><span>🗂️</span><b>البيانات والملفات</b><small>مركز بيانات مساحة المشترك</small></Link><Link href="/followup" className="teacherHubCard"><span>📌</span><b>المتابعة</b><small>الحضور والمهام</small></Link><Link href="/messages" className="teacherHubCard"><span>💬</span><b>التواصل</b><small>واتساب وSMS لأولياء الأمور</small></Link><Link href="/backup" className="teacherHubCard"><span>💾</span><b>نسخة احتياطية</b><small>حالة النسخ والاسترجاع</small></Link><Link href="/evaluation-settings" className="teacherHubCard"><span>⚙️</span><b>إعدادات التقييم والإشراف</b><small>الحسم ولوحة الشرف</small></Link><Link href="/evaluations" className="teacherHubCard"><span>✅</span><b>التقييم والإشراف المدرسي</b><small>تقييمات موثقة للطلاب</small></Link><Link href="/honor" className="teacherHubCard"><span>🥇</span><b>لوحة الشرف</b><small>ترتيب فعلي حسب النقاط</small></Link><Link href="/reports" className="teacherHubCard"><span>📈</span><b>التقارير</b><small>إحصاءات وتصدير CSV</small></Link></div></section>
  <div className="twoCol" style={{marginTop:18}}><section className="card composer"><h2>الوصول السريع</h2><div className="quickGrid"><Link className="quickCard" href="/followup"><b>تسجيل غياب</b><p className="muted">غياب اليوم: {absent}</p></Link><Link className="quickCard" href="/followup"><b>متابعة المهام</b><p className="muted">المسلم وغير المسلم</p></Link><Link className="quickCard" href="/classes"><b>إضافة فصل</b><p className="muted">تنظيم الصفوف</p></Link><Link className="quickCard" href="/messages"><b>رسالة ولي أمر</b><p className="muted">فردية أو جماعية</p></Link></div></section><section className="card composer"><h2>الخصوصية</h2><p className="muted">كل الطلاب والفصول والرسائل والمتابعة مرتبطة بمعرّف مساحة اشتراكك، وسياسات قاعدة البيانات تمنع القراءة من مساحة أخرى.</p><Link className="btn btn-light" href="/subscription">إدارة الاشتراك</Link></section></div>
 </div></DashboardShell>
}
