import { redirect } from 'next/navigation'
import DashboardShell from '@/components/DashboardShell'
import { createClient } from '@/lib/supabase/server'
import { saveStudentPortalSettings } from './actions'
export default async function StudentSettings(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login')
 const {data:m}=await supabase.from('memberships').select('tenant_id,role,tenants(name)').eq('user_id',user.id).maybeSingle();if(!m)redirect('/dashboard')
 const {data:s}=await supabase.from('student_portal_settings').select('*').eq('tenant_id',m.tenant_id).maybeSingle();const can=['tenant_owner','admin'].includes(m.role);const tenant=(m.tenants as any)?.name||'مساحتي التعليمية'
 return <DashboardShell active="/student-settings" tenant={tenant}><div className="bankContent"><div className="pageTitle"><span className="badge">تخصيص</span><h1>إعدادات لوحة الطالب</h1><p className="muted">تحكم بما يظهر للطالب داخل حسابه دون تغيير بياناته الأساسية.</p></div>
 {!can?<div className="notice">هذه الصفحة للمالك أو المدير فقط.</div>:<form action={saveStudentPortalSettings} className="card composer"><div className="formGrid"><label className="field"><span>اسم الجهة الظاهر للطالب</span><input name="school_label" defaultValue={s?.school_label||tenant}/></label><label className="field"><span>اسم المادة / المجال</span><input name="subject_label" defaultValue={s?.subject_label||'التعليم'}/></label></div><h2>الأقسام الظاهرة</h2><div className="settingsChecks"><label className="check"><input type="checkbox" name="show_balance" defaultChecked={s?.show_balance!==false}/><span>الرصيد التعليمي</span></label><label className="check"><input type="checkbox" name="show_points" defaultChecked={s?.show_points!==false}/><span>النقاط</span></label><label className="check"><input type="checkbox" name="show_rewards" defaultChecked={s?.show_rewards!==false}/><span>الجوائز والروليت</span></label><label className="check"><input type="checkbox" name="show_honor_board" defaultChecked={s?.show_honor_board!==false}/><span>لوحة الشرف</span></label><label className="check"><input type="checkbox" name="show_evaluations" defaultChecked={s?.show_evaluations!==false}/><span>التقييمات</span></label><label className="check"><input type="checkbox" name="show_messages" defaultChecked={s?.show_messages!==false}/><span>رسائل المعلم</span></label><label className="check"><input type="checkbox" name="show_achievements" defaultChecked={s?.show_achievements!==false}/><span>الإنجازات والشارات</span></label></div><button className="btn btn-primary">حفظ إعدادات لوحة الطالب</button></form>}
 </div></DashboardShell>
}
